{
    "name": "MTS Connector",
    "category": "MTS",
    "version": "17.0.1.2.1",
    "sequence": 1,
    "author": "OpenG2P (OpenSPP fork)",
    "website": "https://openg2p.org",
    "license": "LGPL-3",
    "depends": ["base", "queue_job"],
    "external_dependencies": {"python": ["jq"]},
    "data": [
        "security/ir.model.access.csv",
        "security/security.xml",
        "views/menuitems.xml",
        "views/mts_connector.xml",
    ],
    "assets": {},
    "demo": [],
    "images": [],
    "application": True,
    "installable": True,
    "auto_install": False,
}
